/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.com.felipeoliveira.view;

import ca.com.felipeoliveira.model.*;
import ca.com.felipeoliveira.viewmodel.ConnexionSQLite;
import ca.com.felipeoliveira.viewmodel.Frames;
import ca.com.felipeoliveira.viewmodel.GererBD;
import ca.com.felipeoliveira.viewmodel.Guichet;
import java.awt.Frame;
import java.lang.StringBuilder;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JTextField;

/**
 *
 * @author felipeoliveira
 */
public class EcranClient extends javax.swing.JFrame {

    /**
     * Creates new form EcranClient
     */
    
    final int CLAVIER_NUMERIQUE_DEPOT = 0;
    final int CLAVIER_NUMERIQUE_RETRAIT = 1;
    final int CLAVIER_NUMERIQUE_TRANSFERT = 2;
    final int CLAVIER_NUMERIQUE_PAIEMENT = 3;
    final int TRANSACTION_DEPOT = 1;
    final int TRANSACTION_RETRAIT = 2;
    final int TRANSACTION_TRANSFERT = 3;
    final int TRANSACTION_FACTURE = 4;
    final double PAIEMENT_FACTURE_TAUX = 1.25;
    final double RETRAIT_MAXIMUN = 1000.0;
    List<CompteCheque> cheques = new ArrayList();
    List<CompteEpargne> epargnes = new ArrayList();
    List<CompteHypothecaire> hypothecaires = new ArrayList();
    MargeDeCredit margeCredit;
    Guichet guichet;
    Frames frame =  new Frames();
    ConnexionSQLite connexion = new ConnexionSQLite();
    GererBD gererBD = new GererBD(connexion); 
    Statement statement = null;
    ResultSet resultSet = null;
    String codeClient;
    int clavierNumeriqueDestin = CLAVIER_NUMERIQUE_DEPOT;
    public EcranClient(String codeClient) {
        initComponents();
        this.codeClient = codeClient;
        remplirComptes();
        mettreAJourCB();
        guichet = gererBD.retournerGuichet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabDepot = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblBoxDepot = new javax.swing.JLabel();
        txtDepot = new javax.swing.JTextField();
        lblCompteDestin1 = new javax.swing.JLabel();
        cbDepotCompteDestin = new javax.swing.JComboBox<>();
        btnDepot = new javax.swing.JButton();
        tabRetrait = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblBoxDepot1 = new javax.swing.JLabel();
        txtRetrait = new javax.swing.JTextField();
        lblCompteDestin2 = new javax.swing.JLabel();
        cbRetraitCompteSource = new javax.swing.JComboBox<>();
        btnRetrait = new javax.swing.JButton();
        tabTransfert = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblBoxTransfert = new javax.swing.JLabel();
        cbTransfertCompteSource = new javax.swing.JComboBox<>();
        lblCompteSource = new javax.swing.JLabel();
        lblCompteDestin = new javax.swing.JLabel();
        cbTransfertCompteDestin = new javax.swing.JComboBox<>();
        btnTransferer = new javax.swing.JButton();
        txtTransfert = new javax.swing.JTextField();
        tabPaiement = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPaiement = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        cbPaiementCompteSource = new javax.swing.JComboBox<>();
        lblCompteSource1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(232, 232, 250));

        jPanel4.setBackground(new java.awt.Color(225, 225, 255));

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(204, 255, 204));
        btn0.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        jButton1.setText("CE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearEntryClick(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(192, 192, 192));
        jTabbedPane1.setForeground(new java.awt.Color(51, 0, 255));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N

        tabDepot.setBackground(new java.awt.Color(218, 218, 218));

        jPanel2.setBackground(new java.awt.Color(222, 222, 222));

        lblBoxDepot.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblBoxDepot.setForeground(new java.awt.Color(102, 102, 102));
        lblBoxDepot.setText("Dépôt");

        txtDepot.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDepot.setText("$00.0");
        txtDepot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepotActionPerformed(evt);
            }
        });

        lblCompteDestin1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCompteDestin1.setForeground(new java.awt.Color(110, 110, 110));
        lblCompteDestin1.setText("Compte destin");

        btnDepot.setText("EFFECTUER DÉPÔT");
        btnDepot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblBoxDepot)
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblCompteDestin1)
                                .addGap(43, 43, 43))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDepotCompteDestin, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtDepot, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 12, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnDepot)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblBoxDepot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDepot, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCompteDestin1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDepotCompteDestin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDepot, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabDepotLayout = new javax.swing.GroupLayout(tabDepot);
        tabDepot.setLayout(tabDepotLayout);
        tabDepotLayout.setHorizontalGroup(
            tabDepotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDepotLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        tabDepotLayout.setVerticalGroup(
            tabDepotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDepotLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DÉPÔT", tabDepot);

        tabRetrait.setBackground(new java.awt.Color(218, 218, 218));

        jPanel3.setBackground(new java.awt.Color(222, 222, 222));

        lblBoxDepot1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblBoxDepot1.setForeground(new java.awt.Color(102, 102, 102));
        lblBoxDepot1.setText("Retrait");

        txtRetrait.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRetrait.setText("$00.0");
        txtRetrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRetraitActionPerformed(evt);
            }
        });

        lblCompteDestin2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCompteDestin2.setForeground(new java.awt.Color(110, 110, 110));
        lblCompteDestin2.setText("Compte source");

        btnRetrait.setText("EFFECTUER RETRAIT");
        btnRetrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetraitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lblBoxDepot1)
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lblCompteDestin2)
                                .addGap(43, 43, 43))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbRetraitCompteSource, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtRetrait, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnRetrait)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblBoxDepot1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRetrait, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCompteDestin2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbRetraitCompteSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnRetrait, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabRetraitLayout = new javax.swing.GroupLayout(tabRetrait);
        tabRetrait.setLayout(tabRetraitLayout);
        tabRetraitLayout.setHorizontalGroup(
            tabRetraitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRetraitLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        tabRetraitLayout.setVerticalGroup(
            tabRetraitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRetraitLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("RETRAIT", tabRetrait);

        tabTransfert.setBackground(new java.awt.Color(225, 225, 255));

        jPanel1.setBackground(new java.awt.Color(216, 216, 254));

        lblBoxTransfert.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblBoxTransfert.setForeground(new java.awt.Color(102, 102, 102));
        lblBoxTransfert.setText("Transfert");

        lblCompteSource.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCompteSource.setForeground(new java.awt.Color(110, 110, 110));
        lblCompteSource.setText("Compte source");

        lblCompteDestin.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCompteDestin.setForeground(new java.awt.Color(110, 110, 110));
        lblCompteDestin.setText("Compte destin");

        cbTransfertCompteDestin.setMinimumSize(new java.awt.Dimension(52, 47));

        btnTransferer.setText("TRANSFERER");
        btnTransferer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransfertActionPerfomed(evt);
            }
        });

        txtTransfert.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTransfert.setText("$00.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(txtTransfert, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(cbTransfertCompteDestin, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTransfertCompteSource, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(lblBoxTransfert)))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnTransferer, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(lblCompteDestin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(lblCompteSource)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBoxTransfert)
                .addGap(37, 37, 37)
                .addComponent(lblCompteSource)
                .addGap(18, 18, 18)
                .addComponent(cbTransfertCompteSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(lblCompteDestin)
                .addGap(18, 18, 18)
                .addComponent(cbTransfertCompteDestin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(txtTransfert, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnTransferer, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout tabTransfertLayout = new javax.swing.GroupLayout(tabTransfert);
        tabTransfert.setLayout(tabTransfertLayout);
        tabTransfertLayout.setHorizontalGroup(
            tabTransfertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTransfertLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        tabTransfertLayout.setVerticalGroup(
            tabTransfertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTransfertLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TRANSFERT", tabTransfert);

        tabPaiement.setBackground(new java.awt.Color(218, 218, 218));

        jLabel1.setText("Code de la Facture");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("000.000.000.000");

        jLabel2.setText("Montant à payer");

        txtPaiement.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPaiement.setText("$00.0");

        jButton2.setText("Payer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayerActionPerfomed(evt);
            }
        });

        lblCompteSource1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCompteSource1.setForeground(new java.awt.Color(110, 110, 110));
        lblCompteSource1.setText("Compte source");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbPaiementCompteSource, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPaiement, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(lblCompteSource1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(lblCompteSource1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbPaiementCompteSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPaiement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout tabPaiementLayout = new javax.swing.GroupLayout(tabPaiement);
        tabPaiement.setLayout(tabPaiementLayout);
        tabPaiementLayout.setHorizontalGroup(
            tabPaiementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPaiementLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        tabPaiementLayout.setVerticalGroup(
            tabPaiementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaiementLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PAIEMENT", tabPaiement);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepotActionPerformed
        //On recupère la valeur saisi
        String valeurSaisi = txtDepot.getText().replace("$", "").replace(",", "");
        double valeur = Double.parseDouble(valeurSaisi);
        int indexCompte = 0;
        //On recupere la compre destin
        String compteDestin = cbDepotCompteDestin.getSelectedItem().toString();
        //On identifie le type de la compte et le numero
        String[] compteChoisi = compteDestin.split(" ");
        String numeroCompteDestin = compteChoisi[1];
        String compteType = compteChoisi[0];
    
        if(compteType.equals("Cheque")){
            System.out.println("Depot ok 1");
            indexCompte = getIndexComptesCheques(numeroCompteDestin, cheques);
            //On effectue le depot dans la compte cheque
            boolean succces = cheques.get(indexCompte).depot(valeur);
            if(succces){
                double solde = cheques.get(indexCompte).getSolde();
                gererBD.enregistrerSolde(numeroCompteDestin, solde);
                //On enregistre la transaction
                gererBD.insererTransaction(TRANSACTION_DEPOT, "", numeroCompteDestin, valeur);
                //On met à jour le ComboBox
                mettreAJourCB();
                System.out.println("Depot succes");
            }
        }
        else if(compteType.equals("Épargne") ){
            indexCompte = getIndexComptesEpargnes(numeroCompteDestin, epargnes);
            //On effectue le depot dans la compte cheque
            boolean succces = epargnes.get(indexCompte).depot(valeur);
            if(succces){
                double solde = epargnes.get(indexCompte).getSolde();
                gererBD.enregistrerSolde(numeroCompteDestin, solde);
                //On enregistre la transaction
                gererBD.insererTransaction(TRANSACTION_DEPOT, "", numeroCompteDestin, valeur);
                //On met à jour le ComboBox
                mettreAJourCB();
                System.out.println("Depot succes");
            }
        }
        else if(compteType.equals("Hypothecaire")){
            indexCompte = getIndexComptesHypothecaire(numeroCompteDestin, hypothecaires);
            //On effectue le depot dans la compte cheque
            boolean succces = hypothecaires.get(indexCompte).depot(valeur);
            if(succces){
                double solde = hypothecaires.get(indexCompte).getSolde();
                gererBD.enregistrerSolde(numeroCompteDestin, solde);
                //On enregistre la transaction
                gererBD.insererTransaction(TRANSACTION_DEPOT, "", numeroCompteDestin, valeur);
                //On met à jour le ComboBox
                mettreAJourCB();
                System.out.println("Depot succes");
            }
        }
        
        
    }//GEN-LAST:event_btnDepotActionPerformed
    
    private int getIndexComptesCheques(String numeroCompte, List<CompteCheque>comptes){
         int numero = 0;
        for(int i = 0; i < comptes.size(); i++){
            if(numeroCompte.equals(comptes.get(i).getNumero())){
                numero = i;
            }
        }
        return numero;
    }
    
    private int getIndexComptesEpargnes(String numeroCompte, List<CompteEpargne>comptes){
         int numero = 0;
        for(int i = 0; i < comptes.size(); i++){
            if(numeroCompte.equals(comptes.get(i).getNumero())){
                numero = i;
            }
        }
        return numero;
    }
    
    private int getIndexComptesHypothecaire(String numeroCompte, List<CompteHypothecaire>comptes){
         int numero = 0;
        for(int i = 0; i < comptes.size(); i++){
            if(numeroCompte.equals(comptes.get(i).getNumero())){
                numero = i;
            }
        }
        return numero;
    }
    
    private void btnRetraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetraitActionPerformed
        //On recupère la valeur saisi
        String valeurSaisi = txtRetrait.getText().replace("$", "").replace(",", "");
        double valeur = Double.parseDouble(valeurSaisi);
        boolean multipleDeDix = (valeur % 10 == 0);
        boolean retraitDansLaLimite = (valeur <= RETRAIT_MAXIMUN);
        int indexCompte = 0;
        boolean soldeGuichetDisponible = (guichet.getSolde() >= valeur);
        
        if(!soldeGuichetDisponible){
            //Si le solde du guiché n'est pas sufisante on afiche la fenetre
            frame.soldeGuichetInsufisant();
        }
        if(!multipleDeDix) frame.exceptionRetrait();
       //On efecture le recrait si la valeur saisi est dans la limite et est multiple de dix
        if(multipleDeDix && retraitDansLaLimite && soldeGuichetDisponible){
            //On recupere la compte source
            String compteSourceItemRetrait = cbRetraitCompteSource.getSelectedItem().toString();
            //On identifie le type de la compte et le numero
            String[] compteChoisi = compteSourceItemRetrait.split(" ");
            String numeroCompteSource = compteChoisi[1];
            String compteType = compteChoisi[0];

            if(compteType.equals("Cheque")){
                indexCompte = getIndexComptesCheques(numeroCompteSource, cheques);
                //On recupere la compreSource
                CompteCheque ccRetrait = cheques.get(indexCompte);
                //On essaye de effecteur le retrait
                boolean succces = ccRetrait.retrait(valeur, margeCredit, gererBD);
                if(succces){
                    double solde = cheques.get(indexCompte).getSolde();
                    gererBD.enregistrerSolde(numeroCompteSource, solde);
                    //On enregistre la transaction
                    gererBD.insererTransaction(TRANSACTION_RETRAIT, numeroCompteSource, "", valeur);
                    //On met à jour le ComboBox
                    mettreAJourCB();
                    System.out.println("Retrait succes");
                    //On met a jour le guichet
                    guichet.retrait(valeur);
                    gererBD.enregistrerSoldeGuichet(guichet.getSolde());
                    System.out.println(guichet.getSolde());
                }
            }
            else if(compteType.equals("Épargne") ){
                indexCompte = getIndexComptesEpargnes(numeroCompteSource, epargnes);
                //On effectue le depot dans la compte cheque
                boolean succces = epargnes.get(indexCompte).retrait(valeur);
                if(succces){
                    double solde = epargnes.get(indexCompte).getSolde();
                    gererBD.enregistrerSolde(numeroCompteSource, solde);
                    //On enregistre la transaction
                    gererBD.insererTransaction(TRANSACTION_RETRAIT, numeroCompteSource , "" , valeur);
                    //On met à jour le ComboBox
                    mettreAJourCB();
                    System.out.println("Retrait succes");
                    //On met a jour le guichet
                    guichet.retrait(valeur);
                    gererBD.enregistrerSoldeGuichet(guichet.getSolde());
                }
            }
        }
    }//GEN-LAST:event_btnRetraitActionPerformed

    private void clavierNumeriqueClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clavierNumeriqueClick
        //On recupère la tab selectionnée
        clavierNumeriqueDestin = jTabbedPane1.getSelectedIndex();
        //On recupère le numero cliqué
        String btnClique = evt.getActionCommand();
    
        //SI l'utilisateur clique sur le tabDepot on processe le clavier numerique dans le champs
        if(clavierNumeriqueDestin == CLAVIER_NUMERIQUE_DEPOT){
            //On recupère la valeur du champs TextField
            String valeurChampTxtDepot =  txtDepot.getText();
            //On fait appel à la methode pour mettre à jour le TxtField
            mettreAJourTxtField(txtDepot, btnClique, valeurChampTxtDepot);
        }
        else if(clavierNumeriqueDestin == CLAVIER_NUMERIQUE_RETRAIT){
            //On recupère la valeur du champs TextField
            String valeurChampTxtRetrait =  txtRetrait.getText();
            //On fait appel à la methode pour mettre à jour le TxtField
            mettreAJourTxtField(txtRetrait, btnClique, valeurChampTxtRetrait);
        }
        else if(clavierNumeriqueDestin == CLAVIER_NUMERIQUE_TRANSFERT){
            //On recupère la valeur du champs TextField
            String valeurChampTxtTransfert =  txtTransfert.getText();
            //On fait appel à la methode pour mettre à jour le TxtField
            mettreAJourTxtField(txtTransfert, btnClique, valeurChampTxtTransfert);
        }
        else if(clavierNumeriqueDestin == CLAVIER_NUMERIQUE_PAIEMENT){
            //On recupère la valeur du champs TextField
            String valeurChampTxtPaiement =  txtPaiement.getText();
            //On fait appel à la methode pour mettre à jour le TxtField
            mettreAJourTxtField(txtPaiement, btnClique, valeurChampTxtPaiement);
        }
        
    }//GEN-LAST:event_clavierNumeriqueClick

    private void txtRetraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRetraitActionPerformed
    
        
    }//GEN-LAST:event_txtRetraitActionPerformed

    private void clearEntryClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearEntryClick
        remetreTxtField();
    }//GEN-LAST:event_clearEntryClick
    
    private void remetreTxtField(){
        txtDepot.setText("$00.0");
        txtRetrait.setText("$00.0");
        txtTransfert.setText("$00.0");
        txtPaiement.setText("$00.0");
    }
    
    private void txtDepotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepotActionPerformed

    private void btnTransfertActionPerfomed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransfertActionPerfomed
        //On recupère la valeur saisi
        String valeurSaisi = txtTransfert.getText().replace("$", "").replace(",", "");
        double valeur = Double.parseDouble(valeurSaisi);
        boolean succes = true;
        int indexCompteSource = 0;
        int indexCompteDestin = 0;
        double soldeCompteDestin = 0;
        double soldeCompteSource;
        
            //On recupere la compte source et compte destin
            String compteSource = cbTransfertCompteSource.getSelectedItem().toString();
            String compteDestinItem = cbTransfertCompteDestin.getSelectedItem().toString();
            
            //On identifie le type de la compte et le numero
            //Compte source
            String[] compteSourceChoisi = compteSource.split(" ");
            String numeroCompteSource = compteSourceChoisi[1];
            String compteSourceType = compteSourceChoisi[0];
            //CompteDestin
            String[] compteDestinChoisi = compteDestinItem.split(" ");
            String numeroCompteDestin = compteDestinChoisi[1];
            String compteDestinType = compteDestinChoisi[0];

            
            
            //On recupere la compte Cheque source et de la compte source
            indexCompteSource = getIndexComptesCheques(numeroCompteSource, cheques);
            
            //on Recupère la compte source
            CompteCheque compteSourceTransfert = cheques.get(indexCompteSource);             
            //On verifie si la compte source est la meme que la compte destin
            boolean memeCompte = (numeroCompteSource.equals(numeroCompteDestin));
            if(memeCompte){
                //on avise l'utilisateur qu'il doit choisir des comptes differentes pour la transaction
                frame.memeCompteTransaction();
            }
            else{
                    //On effectue le transfert dans la compte.
                if(compteDestinType.equals("Cheque")){
                    //On recupere la compte Cheque source et de la compte destin
                    indexCompteDestin = getIndexComptesCheques(numeroCompteDestin, cheques);
                    CompteCheque compteDestin = cheques.get(indexCompteDestin);
                    succes = compteSourceTransfert.transfertSolde(compteDestin, valeur);
                    soldeCompteDestin = compteDestin.getSolde();
                }
                else if(compteDestinType.equals("Épargne")){
                    CompteEpargne compteDestin = epargnes.get(indexCompteDestin);
                    succes = compteSourceTransfert.transfertSolde(compteDestin, valeur);
                    soldeCompteDestin = compteDestin.getSolde();
                }
                else if(compteDestinType.equals("Hypothecaire")){
                    CompteHypothecaire compteDestin = hypothecaires.get(indexCompteDestin);
                    succes = compteSourceTransfert.transfertSolde(compteDestin, valeur);
                    soldeCompteDestin = compteDestin.getSolde();
                }
                else if (compteDestinType.equals("Credit")){
                    MargeDeCredit compteDestin = margeCredit;
                    if(margeCredit.getSolde() > 0){
                        succes = compteSourceTransfert.transfertSolde(compteDestin, valeur);
                        soldeCompteDestin = compteDestin.getSolde();
                    }
                }
                // Si transaction a été bien effectuée, on l'enregistre dans la BD.
                if(succes){
                        //On recupere la solde de la compte source
                        soldeCompteSource = compteSourceTransfert.getSolde();

                        //On enregistre les soldes des comptes source et destin.
                        gererBD.enregistrerSolde(numeroCompteSource, soldeCompteSource);
                        gererBD.enregistrerSolde(numeroCompteDestin, soldeCompteDestin);
                        //On enregistre la transaction
                        gererBD.insererTransaction(TRANSACTION_TRANSFERT, numeroCompteSource, numeroCompteDestin, valeur);
                        //On met à jour le ComboBox
                        mettreAJourCB();
                        System.out.println("Transaction succes");
                }
            }
            
    }//GEN-LAST:event_btnTransfertActionPerfomed

    private void btnPayerActionPerfomed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayerActionPerfomed
        
        //On recupère la valeur saisi
        String valeurSaisi = txtPaiement.getText().replace("$", "").replace(",", "");
        double valeur = Double.parseDouble(valeurSaisi) + PAIEMENT_FACTURE_TAUX;
        int indexCompte = 0;
        
       //On efecture le recrait si la valeur saisi est dans la limite et est multiple de dix
       
            //On recupere la compte source
            String compteSourceItemRetrait = cbPaiementCompteSource.getSelectedItem().toString();
       
            //On identifie le type de la compte et le numero
            String[] compteChoisi = compteSourceItemRetrait.split(" ");
            String numeroCompteSource = compteChoisi[1];
            String compteType = compteChoisi[0];

            if(compteType.equals("Cheque")){
                indexCompte = getIndexComptesCheques(numeroCompteSource, cheques);
                //On recupere la compreSource
                CompteCheque ccRetrait = cheques.get(indexCompte);
                
                //On check la necessite de prendre de credit dans la Marge de Credit
                boolean necessiteCredit = (ccRetrait.getSolde() < valeur);
                //On effectue le depot dans la compte cheque
                boolean succces = cheques.get(indexCompte).retrait(valeur);
                //Si l'utilisateur a besoin d'utilisé le credit
                if(necessiteCredit){
                    //On verifie la valeur moins ce que devrait rester dans la compte
                    double valeurCreditDemande = (ccRetrait.getSolde() - valeur) * (-1);
                    //On essaye de faire la transaction
                    boolean succesCredit = margeCredit.retraitMargeCredit(valeurCreditDemande);
                    //Si la valeur demandé est dans la limite du credit on doit s'assurer que la solde de la compte cheque est à zero
                    if(succesCredit){
                        ccRetrait.setSolde(0);
                        succces = true;
                        System.out.println("solde credit = " + margeCredit.getSolde());
                        //On enregistre la solde du credit
                        boolean soldeCreditEnregistre = gererBD.enregistrerSolde(margeCredit.getNumero(), margeCredit.getSolde());
                        System.out.println("solde credit enregistre:  " + soldeCreditEnregistre);
                    }
                }
                if(succces){
                    double solde = cheques.get(indexCompte).getSolde();
                    gererBD.enregistrerSolde(numeroCompteSource, solde);
                    //On enregistre la transaction
                    gererBD.insererTransaction(TRANSACTION_FACTURE, numeroCompteSource, "", valeur);
                    //On met à jour le ComboBox
                    mettreAJourCB();
                    System.out.println("Facture succes");
                }
            }
            
        
        
    }//GEN-LAST:event_btnPayerActionPerfomed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EcranClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EcranClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EcranClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EcranClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new EcranClient().setVisible(true);
            }
        });
    }
    
    //METHODES 
    private void remplirComptes(){
        //On vide les listes des comptes
        cheques.clear();
        epargnes.clear();
        hypothecaires.clear();
        
        //On ouvre la connexion sql
        connexion.connect();
        statement = connexion.statement();
        String query = "SELECT * FROM tbl_comptes WHERE codeTitulaire = '" + codeClient +"';";
        try{
            resultSet = statement.executeQuery(query);
            
            while(resultSet.next())
            {
                int compteType = resultSet.getInt("type");
                String numero = resultSet.getString("numero");
                double solde = resultSet.getDouble("solde");
                double limite = resultSet.getDouble("limite");
                
                if(compteType == 1){
                    CompteCheque compte = new CompteCheque(numero, codeClient);
                    compte.setSolde(solde);
                    cheques.add(compte);
                }
                else if(compteType == 2){
                    CompteEpargne compte = new CompteEpargne(numero, codeClient);
                    compte.setSolde(solde);
                    epargnes.add(compte);
                }
                else if(compteType == 3){
                    CompteHypothecaire compte = new CompteHypothecaire(numero, codeClient);
                    compte.setSolde(solde);
                    hypothecaires.add(compte);
                }
                else if(compteType == 4){
                    MargeDeCredit compte = new MargeDeCredit(numero, codeClient);
                    compte.setSolde(solde);
                    this.margeCredit = compte;
                }
                
                
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        finally{
         connexion.deconnecter();
        }
    }
    
    private void mettreAJourCB(){
        //On met à jour tous les ComboBox
        remplirCbTransfert();
        remplirCbDepot();
        remplirCbRetrait();
        remplirCbPaiement();
    }
    
    private void remplirCbTransfert(){
        //On vide le CB
        cbTransfertCompteSource.removeAllItems();
        cbTransfertCompteDestin.removeAllItems();
        
        //On ajoute les comptes cheques de la compte source
        ajouterCbCheques(cheques.size(), cbTransfertCompteSource);
        //On ajoute les comptes destins
        ajouterCbCheques(cheques.size(), cbTransfertCompteDestin);
        ajouterCbEpargnes(epargnes.size(), cbTransfertCompteDestin);
        ajouterCbHypothecaires(hypothecaires.size(), cbTransfertCompteDestin);
        AjouterCbMargeCredit(margeCredit, cbTransfertCompteDestin);
    }
    
    private void remplirCbRetrait(){
        //On vide le CB
        cbRetraitCompteSource.removeAllItems();
        
        //On ajoute les comptes cheques
        ajouterCbCheques(cheques.size(), cbRetraitCompteSource);
        //On ajoute les comptes epargnes
        ajouterCbEpargnes(epargnes.size(), cbRetraitCompteSource);
    }
    
    private void remplirCbDepot(){
        //On vide le CB
        cbDepotCompteDestin.removeAllItems();
        
        //On ajoute les comptes cheques
        ajouterCbCheques(cheques.size(), cbDepotCompteDestin);
        //On ajoute les comptes epargnes
        ajouterCbEpargnes(epargnes.size(), cbDepotCompteDestin);
        //On ajoute les comptes hypothecaire
        ajouterCbHypothecaires(hypothecaires.size(), cbDepotCompteDestin);
    }
    
    private void remplirCbPaiement(){
        //On vide le CB
        cbPaiementCompteSource.removeAllItems();
        
        //On ajoute les comptes cheques
        ajouterCbCheques(cheques.size(), cbPaiementCompteSource);
    }
    
    public void AjouterCbMargeCredit(MargeDeCredit mc, JComboBox cb){
        if(mc != null){
            //On arroundi la solde de la compte
            double solde = mc.getSolde();
            //On utilise le NumberFormat pour afficher la valeur en dolar
            Locale locale = new Locale("en", "US");
            NumberFormat fmt = NumberFormat.getCurrencyInstance(locale);
            String soldeFormate = fmt.format(solde);
            //On cree une string pour l'item
            String cbItem = "Credit "+ mc.getNumero() + " : Solde " + soldeFormate;
            //On ajoute l'item au CB
            cb.addItem(cbItem);
        }
    }
    
    public void ajouterCbCheques(int quantiteCheques, JComboBox cb){
        for(int i = 0; i < quantiteCheques; i++ ){
            //On arroundi la solde de la compte
            double solde = cheques.get(i).getSolde();
            //On utilise le NumberFormat pour afficher la valeur en dolar
            Locale locale = new Locale("en", "US");
            NumberFormat fmt = NumberFormat.getCurrencyInstance(locale);
            String soldeFormate = fmt.format(solde);
            //On cree une string pour l'item
            String cbItem = "Cheque "+ cheques.get(i).getNumero()+ " : Solde " + soldeFormate;
            //On ajoute l'item au CB
            cb.addItem(cbItem);
        }
    }
    
    public void ajouterCbEpargnes(int quantiteEpargnes, JComboBox cb){
        for(int i = 0; i < quantiteEpargnes; i++ ){
            //On arroundi la solde de la compte
            double solde = epargnes.get(i).getSolde();
            //On utilise le NumberFormat pour afficher la valeur en dolar
            Locale locale = new Locale("en", "US");
            NumberFormat fmt = NumberFormat.getCurrencyInstance(locale);
            String soldeFormate = fmt.format(solde);
            //On cree une string pour l'item
            String cbItem = "Épargne "+ epargnes.get(i).getNumero()+ " : Solde " + soldeFormate;
            //On ajoute l'item au CB
            cb.addItem(cbItem);
        }
    }
    
    public void ajouterCbHypothecaires(int quantiteHypothecaires, JComboBox cb){
        for(int i = 0; i < quantiteHypothecaires; i++ ){
            //On arroundi la solde de la compte
            double solde = hypothecaires.get(i).getSolde();
            //On utilise le NumberFormat pour afficher la valeur en dolar
            Locale locale = new Locale("en", "US");
            NumberFormat fmt = NumberFormat.getCurrencyInstance(locale);
            String soldeFormate = fmt.format(solde);
            //On cree une string pour l'item
            String cbItem = "Hypothecaire "+ hypothecaires.get(i).getNumero()+ " : Solde " + soldeFormate;
            //On ajoute l'item au CB
            cb.addItem(cbItem);
        }
    }
    
    private void mettreAJourTxtField(JTextField textField, String numeroSaisi, String txtDepotSaisie){
        //On enleve le caractère special du NumberFormat
        txtDepotSaisie = txtDepotSaisie.replace("$", "").replace(".", "").replace(",", "") + numeroSaisi;
        String txtRemetrePoint = new StringBuilder(txtDepotSaisie).insert(txtDepotSaisie.length()-2, ".").toString();
        double numeroAAficher = Double.parseDouble(txtRemetrePoint);
        //On utilise le NumberFormat pour afficher la valeur en dolar
        Locale locale = new Locale("en", "US");
        NumberFormat fmt = NumberFormat.getCurrencyInstance(locale);
        //On remet la valeur dans le textField
        textField.setText(fmt.format(numeroAAficher));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnDepot;
    private javax.swing.JButton btnRetrait;
    private javax.swing.JButton btnTransferer;
    private javax.swing.JComboBox<String> cbDepotCompteDestin;
    private javax.swing.JComboBox<String> cbPaiementCompteSource;
    private javax.swing.JComboBox<String> cbRetraitCompteSource;
    private javax.swing.JComboBox<String> cbTransfertCompteDestin;
    private javax.swing.JComboBox<String> cbTransfertCompteSource;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBoxDepot;
    private javax.swing.JLabel lblBoxDepot1;
    private javax.swing.JLabel lblBoxTransfert;
    private javax.swing.JLabel lblCompteDestin;
    private javax.swing.JLabel lblCompteDestin1;
    private javax.swing.JLabel lblCompteDestin2;
    private javax.swing.JLabel lblCompteSource;
    private javax.swing.JLabel lblCompteSource1;
    private javax.swing.JPanel tabDepot;
    private javax.swing.JPanel tabPaiement;
    private javax.swing.JPanel tabRetrait;
    private javax.swing.JPanel tabTransfert;
    private javax.swing.JTextField txtDepot;
    private javax.swing.JTextField txtPaiement;
    private javax.swing.JTextField txtRetrait;
    private javax.swing.JTextField txtTransfert;
    // End of variables declaration//GEN-END:variables
}
