/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.com.felipeoliveira.view;

import ca.com.felipeoliveira.model.*;
import ca.com.felipeoliveira.viewmodel.ConnexionSQLite;
import java.lang.StringBuilder;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JComponent;

/**
 *
 * @author felipeoliveira
 */
public class EcranClient extends javax.swing.JFrame {

    /**
     * Creates new form EcranClient
     */
    
    int CLAVIER_NUMERIQUE_DEPOT = 0;
    int CLAVIER_NUMERIQUE_RETRAIT = 1;
    int CLAVIER_NUMERIQUE_TRANSFERT = 2;
    int CLAVIER_NUMERIQUE_PAIEMENT = 3;
    
    List<CompteCheque> cheques = new ArrayList();
    List<CompteEpargne> epargnes = new ArrayList();
    List<CompteHypothecaire> hypothecaires = new ArrayList();
    MargeDeCredit margeCredit;
    
    ConnexionSQLite connexion = new ConnexionSQLite();
    Statement statement = null;
    ResultSet resultSet = null;
    
    String codeClient;
    
    int clavierNumeriqueDestin = CLAVIER_NUMERIQUE_DEPOT;
    public EcranClient(String codeClient) {
        initComponents();
        this.codeClient = codeClient;
        remplirComptes();
        remplirCbDepot();
        remplirCbTransfert();
        remplirCbRetrait();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabDepot = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblBoxDepot = new javax.swing.JLabel();
        txtDepot = new javax.swing.JTextField();
        lblCompteDestin1 = new javax.swing.JLabel();
        cbDepotCompteDestin = new javax.swing.JComboBox<>();
        btnDepot = new javax.swing.JButton();
        tabRetrait = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblBoxDepot1 = new javax.swing.JLabel();
        txtRetrait = new javax.swing.JTextField();
        lblCompteDestin2 = new javax.swing.JLabel();
        cbRetraitCompteSource = new javax.swing.JComboBox<>();
        btnRetrait = new javax.swing.JButton();
        tabTransfert = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblBoxTransfert = new javax.swing.JLabel();
        cbTransfertCompteSource = new javax.swing.JComboBox<>();
        lblCompteSource = new javax.swing.JLabel();
        lblCompteDestin = new javax.swing.JLabel();
        cbTransfertCompteDestin = new javax.swing.JComboBox<>();
        btnTransferer = new javax.swing.JButton();
        txtTransfert = new javax.swing.JTextField();
        tabPaiement = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPaiement = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(232, 232, 250));

        jPanel4.setBackground(new java.awt.Color(225, 225, 255));

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(204, 255, 204));
        btn0.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clavierNumeriqueClick(evt);
            }
        });

        jButton1.setText("CE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearEntryClick(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn0, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(192, 192, 192));
        jTabbedPane1.setForeground(new java.awt.Color(51, 0, 255));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N

        tabDepot.setBackground(new java.awt.Color(218, 218, 218));

        jPanel2.setBackground(new java.awt.Color(222, 222, 222));

        lblBoxDepot.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblBoxDepot.setForeground(new java.awt.Color(102, 102, 102));
        lblBoxDepot.setText("Dépôt");

        txtDepot.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDepot.setText(".0");

        lblCompteDestin1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCompteDestin1.setForeground(new java.awt.Color(110, 110, 110));
        lblCompteDestin1.setText("Compte destin");

        btnDepot.setText("EFFECTUER DÉPÔT");
        btnDepot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblBoxDepot)
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblCompteDestin1)
                                .addGap(43, 43, 43))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDepotCompteDestin, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtDepot, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 12, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnDepot)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblBoxDepot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDepot, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCompteDestin1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbDepotCompteDestin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDepot, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabDepotLayout = new javax.swing.GroupLayout(tabDepot);
        tabDepot.setLayout(tabDepotLayout);
        tabDepotLayout.setHorizontalGroup(
            tabDepotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDepotLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        tabDepotLayout.setVerticalGroup(
            tabDepotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDepotLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DÉPÔT", tabDepot);

        tabRetrait.setBackground(new java.awt.Color(218, 218, 218));

        jPanel3.setBackground(new java.awt.Color(222, 222, 222));

        lblBoxDepot1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblBoxDepot1.setForeground(new java.awt.Color(102, 102, 102));
        lblBoxDepot1.setText("Retrait");

        txtRetrait.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRetrait.setText(".0");
        txtRetrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRetraitActionPerformed(evt);
            }
        });

        lblCompteDestin2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCompteDestin2.setForeground(new java.awt.Color(110, 110, 110));
        lblCompteDestin2.setText("Compte source");

        btnRetrait.setText("EFFECTUER RETRAIT");
        btnRetrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetraitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lblBoxDepot1)
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lblCompteDestin2)
                                .addGap(43, 43, 43))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbRetraitCompteSource, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtRetrait, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnRetrait)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblBoxDepot1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRetrait, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCompteDestin2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbRetraitCompteSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnRetrait, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabRetraitLayout = new javax.swing.GroupLayout(tabRetrait);
        tabRetrait.setLayout(tabRetraitLayout);
        tabRetraitLayout.setHorizontalGroup(
            tabRetraitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRetraitLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        tabRetraitLayout.setVerticalGroup(
            tabRetraitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRetraitLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("RETRAIT", tabRetrait);

        tabTransfert.setBackground(new java.awt.Color(225, 225, 255));

        jPanel1.setBackground(new java.awt.Color(216, 216, 254));

        lblBoxTransfert.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblBoxTransfert.setForeground(new java.awt.Color(102, 102, 102));
        lblBoxTransfert.setText("Transfert");

        lblCompteSource.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCompteSource.setForeground(new java.awt.Color(110, 110, 110));
        lblCompteSource.setText("Compte source");

        lblCompteDestin.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblCompteDestin.setForeground(new java.awt.Color(110, 110, 110));
        lblCompteDestin.setText("Compte destin");

        btnTransferer.setText("TRANSFERER");

        txtTransfert.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTransfert.setText(".0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lblBoxTransfert))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lblCompteSource))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lblCompteDestin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTransfertCompteDestin, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTransfertCompteSource, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtTransfert, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnTransferer, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBoxTransfert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCompteSource)
                .addGap(2, 2, 2)
                .addComponent(cbTransfertCompteSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCompteDestin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTransfertCompteDestin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTransfert, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTransferer, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabTransfertLayout = new javax.swing.GroupLayout(tabTransfert);
        tabTransfert.setLayout(tabTransfertLayout);
        tabTransfertLayout.setHorizontalGroup(
            tabTransfertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTransfertLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        tabTransfertLayout.setVerticalGroup(
            tabTransfertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTransfertLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TRANSFERT", tabTransfert);

        tabPaiement.setBackground(new java.awt.Color(218, 218, 218));

        jLabel1.setText("Code de la Facture");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("000.000.000.000");

        jLabel2.setText("Montant à payer");

        txtPaiement.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPaiement.setText(".0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(144, 144, 144))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPaiement, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPaiement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabPaiementLayout = new javax.swing.GroupLayout(tabPaiement);
        tabPaiement.setLayout(tabPaiementLayout);
        tabPaiementLayout.setHorizontalGroup(
            tabPaiementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPaiementLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        tabPaiementLayout.setVerticalGroup(
            tabPaiementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPaiementLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PAIEMENT", tabPaiement);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDepotActionPerformed

    private void btnRetraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetraitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRetraitActionPerformed

    private void clavierNumeriqueClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clavierNumeriqueClick
        //On recupère la tab selectionnée
        clavierNumeriqueDestin = jTabbedPane1.getSelectedIndex();
        //SI l'utilisateur clique sur le tabDepot on processe le clavier numerique dans le champs
        if(clavierNumeriqueDestin == CLAVIER_NUMERIQUE_DEPOT){
            //On recupère le numero cliqué
            String btnClique = evt.getActionCommand();
            //On recupere la valeur du txtDepot plus le numero choisi
            String txtDepotSaisie = txtDepot.getText().replace(".","") + btnClique;
            //On retire les dernies 6 caractères.
            double valeurDepot = Double.parseDouble(txtDepotSaisie);
            if(valeurDepot > 100){
               txtDepotSaisie = txtDepotSaisie.replaceFirst("^0+(?!$)", "");
            }
            String txtAAfficher = new StringBuilder(txtDepotSaisie).insert(txtDepotSaisie.length()-2, ".").toString();
            //On affiche à l'ecran
            txtDepot.setText(txtAAfficher);
        }
        else if(clavierNumeriqueDestin == CLAVIER_NUMERIQUE_RETRAIT){
            //On recupère le numero cliqué
            String btnClique = evt.getActionCommand();
            //On recupere la valeur du txtCodeClient plus le numero choisi
            String txtRetraitSaisi = txtRetrait.getText().replace(".","") + btnClique;
            //On retire les dernies 6 caractères.
            double transfertValeur = Double.parseDouble(txtRetraitSaisi);
            if(transfertValeur > 100){
               txtRetraitSaisi = txtRetraitSaisi.replaceFirst("^0+(?!$)", "");
            }
            String txtAAfficher = new StringBuilder(txtRetraitSaisi).insert(txtRetraitSaisi.length()-2, ".").toString();
            //On affiche à l'ecran
            txtRetrait.setText(txtAAfficher);
        }
        else if(clavierNumeriqueDestin == CLAVIER_NUMERIQUE_TRANSFERT){
            //On recupère le numero cliqué
            String btnClique = evt.getActionCommand();
            //On recupere la valeur du txtCodeClient plus le numero choisi
            String txtTransfertSaisi = txtTransfert.getText().replace(".","") + btnClique;
            //On retire les dernies 6 caractères.
            double transfertValeur = Double.parseDouble(txtTransfertSaisi);
            if(transfertValeur > 100){
               txtTransfertSaisi = txtTransfertSaisi.replaceFirst("^0+(?!$)", "");
            }
            String txtAAfficher = new StringBuilder(txtTransfertSaisi).insert(txtTransfertSaisi.length()-2, ".").toString();
            //On affiche à l'ecran
            txtTransfert.setText(txtAAfficher);
        }
        else if(clavierNumeriqueDestin == CLAVIER_NUMERIQUE_PAIEMENT){
            //On recupère le numero cliqué
            String btnClique = evt.getActionCommand();
            //On recupere la valeur du txtCodeClient plus le numero choisi
            String txtPaiementSaisi = txtPaiement.getText().replace(".","") + btnClique;
            //On retire les dernies 6 caractères.
            double transfertValeur = Double.parseDouble(txtPaiementSaisi);
            if(transfertValeur > 100){
               txtPaiementSaisi = txtPaiementSaisi.replaceFirst("^0+(?!$)", "");
            }
            String txtAAfficher = new StringBuilder(txtPaiementSaisi).insert(txtPaiementSaisi.length()-2, ".").toString();
            //On affiche à l'ecran
            txtPaiement.setText(txtAAfficher);
        }
        
    }//GEN-LAST:event_clavierNumeriqueClick

    private void txtRetraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRetraitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRetraitActionPerformed

    private void clearEntryClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearEntryClick
        txtDepot.setText(".0");
        txtRetrait.setText(".0");
        txtTransfert.setText(".0");
        txtPaiement.setText(".0");
    }//GEN-LAST:event_clearEntryClick

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EcranClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EcranClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EcranClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EcranClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new EcranClient().setVisible(true);
            }
        });
    }
    
    //METHODES 
    private void remplirComptes(){
        //On vide les listes des comptes
        cheques.clear();
        epargnes.clear();
        hypothecaires.clear();
        
        //On ouvre la connexion sql
        connexion.connect();
        statement = connexion.statement();
        String query = "SELECT * FROM tbl_comptes WHERE codeTitulaire = '" + codeClient +"';";
        try{
            resultSet = statement.executeQuery(query);
            
            while(resultSet.next())
            {
                int compteType = resultSet.getInt("type");
                String numero = resultSet.getString("numero");
                double solde = resultSet.getDouble("solde");
                double limite = resultSet.getDouble("limite");
                
                if(compteType == 1){
                    CompteCheque compte = new CompteCheque(numero, codeClient);
                    compte.setSolde(solde);
                    cheques.add(compte);
                }
                else if(compteType == 2){
                    CompteEpargne compte = new CompteEpargne(numero, codeClient);
                    compte.setSolde(solde);
                    epargnes.add(compte);
                }
                else if(compteType == 3){
                    CompteHypothecaire compte = new CompteHypothecaire(numero, codeClient);
                    compte.setSolde(solde);
                    hypothecaires.add(compte);
                }
                else if(compteType == 4){
                    MargeDeCredit compte = new MargeDeCredit(numero, codeClient);
                    this.margeCredit = compte;
                }
                
                
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        finally{
         connexion.deconnecter();
        }
    }
    private void remplirCbTransfert(){
        //On vide le CB
        cbTransfertCompteSource.removeAllItems();
        cbTransfertCompteDestin.removeAllItems();
        
        //On ajoute les comptes cheques de la compte source
        ajouterCbCheques(cheques.size(), cbTransfertCompteSource);
        //On ajoute les comptes destins
        ajouterCbCheques(cheques.size(), cbTransfertCompteDestin);
        ajouterCbEpargnes(epargnes.size(), cbTransfertCompteDestin);
        ajouterCbHypothecaires(hypothecaires.size(), cbTransfertCompteDestin);
        AjouterCbMargeCredit(margeCredit, cbTransfertCompteDestin);
    }
    private void remplirCbRetrait(){
        //On vide le CB
        cbRetraitCompteSource.removeAllItems();
        
        //On ajoute les comptes cheques
        ajouterCbCheques(cheques.size(), cbRetraitCompteSource);
        //On ajoute les comptes epargnes
        ajouterCbEpargnes(epargnes.size(), cbRetraitCompteSource);
    }
    private void remplirCbDepot(){
        //On vide le CB
        cbDepotCompteDestin.removeAllItems();
        
        //On ajoute les comptes cheques
        ajouterCbCheques(cheques.size(), cbDepotCompteDestin);
        //On ajoute les comptes epargnes
        ajouterCbEpargnes(epargnes.size(), cbDepotCompteDestin);
        //On ajoute les comptes hypothecaire
        ajouterCbHypothecaires(hypothecaires.size(), cbDepotCompteDestin);
    }
    
    public void AjouterCbMargeCredit(MargeDeCredit mc, JComboBox cb){
            //On arroundi la solde de la compte
            double solde = mc.getSolde();
            DecimalFormat df = new DecimalFormat("#.##");      
            solde = Double.valueOf(df.format(solde));
            //On cree une string pour l'item
            String cbItem = "Cheque "+ mc.getNumero() + " : Solde $" + solde;
            //On ajoute l'item au CB
            cb.addItem(cbItem);
    }
    
    public void ajouterCbCheques(int quantiteCheques, JComboBox cb){
        for(int i = 0; i < quantiteCheques; i++ ){
            //On arroundi la solde de la compte
            double solde = cheques.get(i).getSolde();
            DecimalFormat df = new DecimalFormat("#.##");      
            solde = Double.valueOf(df.format(solde));
            //On cree une string pour l'item
            String cbItem = "Cheque "+ cheques.get(i).getNumero()+ " : Solde $" + solde;
            //On ajoute l'item au CB
            cb.addItem(cbItem);
        }
    }
    
    public void ajouterCbEpargnes(int quantiteEpargnes, JComboBox cb){
        for(int i = 0; i < quantiteEpargnes; i++ ){
            //On arroundi la solde de la compte
            double solde = epargnes.get(i).getSolde();
            DecimalFormat df = new DecimalFormat("#.##");      
            solde = Double.valueOf(df.format(solde));
            //On cree une string pour l'item
            String cbItem = "Épargne "+ epargnes.get(i).getNumero()+ " : Solde $" + solde;
            //On ajoute l'item au CB
            cb.addItem(cbItem);
        }
    }
    
    public void ajouterCbHypothecaires(int quantiteHypothecaires, JComboBox cb){
        for(int i = 0; i < quantiteHypothecaires; i++ ){
            //On arroundi la solde de la compte
            double solde = hypothecaires.get(i).getSolde();
            DecimalFormat df = new DecimalFormat("#.##");      
            solde = Double.valueOf(df.format(solde));
            //On cree une string pour l'item
            String cbItem = "Hypothecaire "+ hypothecaires.get(i).getNumero()+ " : Solde $" + solde;
            //On ajoute l'item au CB
            cb.addItem(cbItem);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnDepot;
    private javax.swing.JButton btnRetrait;
    private javax.swing.JButton btnTransferer;
    private javax.swing.JComboBox<String> cbDepotCompteDestin;
    private javax.swing.JComboBox<String> cbRetraitCompteSource;
    private javax.swing.JComboBox<String> cbTransfertCompteDestin;
    private javax.swing.JComboBox<String> cbTransfertCompteSource;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBoxDepot;
    private javax.swing.JLabel lblBoxDepot1;
    private javax.swing.JLabel lblBoxTransfert;
    private javax.swing.JLabel lblCompteDestin;
    private javax.swing.JLabel lblCompteDestin1;
    private javax.swing.JLabel lblCompteDestin2;
    private javax.swing.JLabel lblCompteSource;
    private javax.swing.JPanel tabDepot;
    private javax.swing.JPanel tabPaiement;
    private javax.swing.JPanel tabRetrait;
    private javax.swing.JPanel tabTransfert;
    private javax.swing.JTextField txtDepot;
    private javax.swing.JTextField txtPaiement;
    private javax.swing.JTextField txtRetrait;
    private javax.swing.JTextField txtTransfert;
    // End of variables declaration//GEN-END:variables
}
