/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.com.felipeoliveira.view;

import ca.com.felipeoliveira.model.Client;
import ca.com.felipeoliveira.model.CompteCheque;
import ca.com.felipeoliveira.model.CompteEpargne;
import ca.com.felipeoliveira.model.CompteHypothecaire;
import ca.com.felipeoliveira.model.MargeDeCredit;
import ca.com.felipeoliveira.model.Transaction;
import ca.com.felipeoliveira.viewmodel.ConnexionSQLite;
import ca.com.felipeoliveira.viewmodel.Frames;
import ca.com.felipeoliveira.viewmodel.GererBD;
import ca.com.felipeoliveira.viewmodel.GererEntrees;
import ca.com.felipeoliveira.viewmodel.Guichet;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;

/**
 *
 * @author felipeoliveira
 */
public class EcranAdmin extends javax.swing.JFrame {

    
    List<CompteCheque> cheques = new ArrayList();
    List<CompteCheque> chequesBanque;
    List<MargeDeCredit> creditsBanque; 
    List<CompteEpargne> epargnes = new ArrayList();
    List<CompteHypothecaire> hypothecaires = new ArrayList();
    List<Transaction> transactions;
    MargeDeCredit margeCredit;
    ConnexionSQLite connexion = new ConnexionSQLite();
    GererBD gererBD = new GererBD(connexion); 
    Statement statement = null;
    ResultSet resultSet = null;
    String codeClient;
    Guichet guichet;
    Client client;
    Frames frame = new Frames();
    GererEntrees entree = new GererEntrees();
    /**
     * Creates new form EcranAdmin
     */
    public EcranAdmin() {
        initComponents();
        txtLimite.setEnabled(false);
        btnModifierLimite.setEnabled(false);
        btnCreerCompte.setEnabled(false);
        btnPrelevementHypothecaire.setEnabled(false);
        guichet = gererBD.retournerGuichet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblPrenomC = new javax.swing.JLabel();
        lblNomC = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomNvClient = new javax.swing.JTextField();
        txtPrenomNvClient = new javax.swing.JTextField();
        txtTelNvClient = new javax.swing.JTextField();
        txtNIPNvClient = new javax.swing.JTextField();
        btnAjouterClient = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodeClientChercher = new javax.swing.JTextField();
        btnChercherClient = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        lblCodeClient = new javax.swing.JLabel();
        lblNomPrenomClient = new javax.swing.JLabel();
        lblTelephoneClient = new javax.swing.JLabel();
        btnClientStatus = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTransactions = new javax.swing.JList<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbTypeCompteCreer = new javax.swing.JComboBox<>();
        btnCreerCompte = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtValeurPrelevementHypothecaire = new javax.swing.JTextField();
        cbHypothecaires = new javax.swing.JComboBox<>();
        btnPrelevementHypothecaire = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblLimite = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLimite = new javax.swing.JTextField();
        btnModifierLimite = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblCreditSolde = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnAjouterArgent = new javax.swing.JButton();
        btnInteret = new javax.swing.JButton();
        btnTauxCredit = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 196));

        jPanel2.setBackground(new java.awt.Color(253, 253, 195));

        lblPrenomC.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblPrenomC.setForeground(new java.awt.Color(102, 102, 102));
        lblPrenomC.setText("Prenom:");

        lblNomC.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblNomC.setForeground(new java.awt.Color(102, 102, 102));
        lblNomC.setText("Nom:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("NIP:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Telephone:");

        btnAjouterClient.setText("AJOUTER CLIENT");
        btnAjouterClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(lblPrenomC)
                    .addComponent(lblNomC)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomNvClient, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrenomNvClient, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelNvClient, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNIPNvClient, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAjouterClient, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomC)
                    .addComponent(txtNomNvClient, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrenomC)
                    .addComponent(txtPrenomNvClient, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelNvClient, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNIPNvClient, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(btnAjouterClient, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CREER CLIENT", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 196));

        jLabel1.setText("Code client:");

        btnChercherClient.setText("CHERCHER CLIENT");
        btnChercherClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChercherClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodeClientChercher, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChercherClient, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodeClientChercher, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChercherClient, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lblCodeClient.setText("Code Client");

        lblNomPrenomClient.setText("Nom, prenom");

        lblTelephoneClient.setText("Telephone");

        btnClientStatus.setText("CLIENT ACTIF");
        btnClientStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lblCodeClient)
                .addGap(136, 136, 136)
                .addComponent(lblNomPrenomClient)
                .addGap(110, 110, 110)
                .addComponent(lblTelephoneClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClientStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodeClient)
                    .addComponent(lblNomPrenomClient)
                    .addComponent(lblTelephoneClient)
                    .addComponent(btnClientStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Historique de transactions");

        jScrollPane1.setViewportView(listTransactions);

        jPanel10.setBackground(new java.awt.Color(255, 204, 204));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Creer compte");

        cbTypeCompteCreer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cheque", "Épargne", "Hypothecaire", "Marge de crédit" }));

        btnCreerCompte.setText("CREER COMPTE");
        btnCreerCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreerCompteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbTypeCompteCreer, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCreerCompte, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTypeCompteCreer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnCreerCompte, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(204, 204, 255));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Prelevement hypothecaire");

        jLabel7.setText("Valeur");

        cbHypothecaires.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnPrelevementHypothecaire.setText("PRELEVEMENT");
        btnPrelevementHypothecaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrelevementHypothecaireActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPrelevementHypothecaire, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(cbHypothecaires, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(txtValeurPrelevementHypothecaire, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbHypothecaires, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtValeurPrelevementHypothecaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrelevementHypothecaire, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(204, 255, 204));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText("Marge de crédit");

        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Limite:");

        lblLimite.setText("setLimite");

        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Modifier limite");

        txtLimite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLimiteActionPerformed(evt);
            }
        });

        btnModifierLimite.setText("MODIFIER LIMITE");
        btnModifierLimite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierLimiteActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText("Solde:");

        lblCreditSolde.setText("setLimite");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnModifierLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLimite)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCreditSolde)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblLimite)
                    .addComponent(jLabel11)
                    .addComponent(lblCreditSolde))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModifierLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("GERER COMPTE", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 196));

        btnAjouterArgent.setText("AJOUTER $5000");
        btnAjouterArgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterArgentActionPerformed(evt);
            }
        });

        btnInteret.setText("PAYER INTÉRÊT AUX COMPTES CHEQUES");
        btnInteret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInteretActionPerformed(evt);
            }
        });

        btnTauxCredit.setText("CHARGER INTÉRÊT AUX CREDITS");
        btnTauxCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTauxCreditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnAjouterArgent, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTauxCredit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInteret, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnInteret, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addComponent(btnAjouterArgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(94, 94, 94)
                .addComponent(btnTauxCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("GERER GUICHET", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterClientActionPerformed
        //On recupère les entrées
        String nomNvClient = txtNomNvClient.getText();
        String prenomNvClient = txtPrenomNvClient.getText();
        String telNvClient = txtTelNvClient.getText();
        String nipNvClient = txtNIPNvClient.getText();
        String codeNvClient = gererBD.recupererNumeroClient();
        
        //On verifie la validité
        boolean nomValide = entree.isFullname(nomNvClient);
        boolean prenomValide = entree.isFullname(prenomNvClient);
        boolean telValide = entree.isTelFifteenChars(telNvClient);
        boolean nipValide = (entree.isFourDigits(nipNvClient) && entree.isInt(nipNvClient));
        
        if(nomValide && prenomValide && telValide && nipValide){
            boolean succes = gererBD.insererClient(codeNvClient, nomNvClient, prenomNvClient, telNvClient, nipNvClient);
            if(succes){
                succes = gererBD.insererCompte(codeNvClient, 1);
                frame.compteClientCree(codeNvClient);
                //On vide les champs txt
                txtNomNvClient.setText("");
                txtPrenomNvClient.setText("");
                txtTelNvClient.setText("");
                txtNIPNvClient.setText("");
            }
        }
    }//GEN-LAST:event_btnAjouterClientActionPerformed

    private void btnChercherClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChercherClientActionPerformed
        //On recupere le code saisi
        String codeClientRecherche = txtCodeClientChercher.getText();
        client = gererBD.retournerClient(codeClientRecherche);
        if(client != null){
            listTransactions.setEnabled(true);
            //On active les boutons
            btnCreerCompte.setEnabled(true);
            btnPrelevementHypothecaire.setEnabled(true);
            //On set le code du client
            codeClient = codeClientRecherche;
            //On affiche les informations du client trouvé
            lblCodeClient.setText(client.getCodeClient());
            lblNomPrenomClient.setText(client.getNom() + ", " + client.getPrenom());
            lblTelephoneClient.setText(client.getTelephone());
            //On remplit les comptes
            remplirComptes();
            //On remplit le cb
            remplirCbHypothecaires();
            //On verifie si le client une marge de credit
            margeCredit = gererBD.retournerCredit(codeClient);
            if(margeCredit != null){
                lblLimite.setText("" + margeCredit.getLimite());
                txtLimite.setEnabled(true);
                btnModifierLimite.setEnabled(true);
                lblCreditSolde.setText(String.format("%.2f", margeCredit.getSolde()));
            }
            else {
                txtLimite.setEnabled(false);
            }
            //On set le status de la compte
            if(client.getEsssaieLogin() < 3)
                btnClientStatus.setText("CLIENT ACTIF");
            else
                btnClientStatus.setText("CLIENT BLOQUÉ");
            //On recupere l'historique de transactions
            transactions = gererBD.retournerTransactions(codeClient);
            //On remplit la liste des transactions
            remplirListeTransactions();
        }
        else{
            //to do client pas trouvé
            txtLimite.setEnabled(false);
            btnModifierLimite.setEnabled(false);
            btnCreerCompte.setEnabled(false);
            btnPrelevementHypothecaire.setEnabled(false);
            listTransactions.setEnabled(false);
            frame.clientNomTrouve();
        }
    }//GEN-LAST:event_btnChercherClientActionPerformed

    private void btnCreerCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreerCompteActionPerformed
        //On selectionne
        String TypeCompteSelectionne = cbTypeCompteCreer.getSelectedItem().toString();
        if(TypeCompteSelectionne.equals("Cheque"))
            gererBD.insererCompte(codeClient, 1);
        if(TypeCompteSelectionne.equals("Épargne"))
            gererBD.insererCompte(codeClient, 2);
        if(TypeCompteSelectionne.equals("Hypothecaire"))
            gererBD.insererCompte(codeClient, 3);
        if(TypeCompteSelectionne.equals("Marge de crédit")){
            if(margeCredit == null)
                gererBD.insererCompte(codeClient, 4);
            else {
                // Marge credit existe deja
            }
        }
            
    }//GEN-LAST:event_btnCreerCompteActionPerformed

    private void txtLimiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLimiteActionPerformed
        
        
    }//GEN-LAST:event_txtLimiteActionPerformed

    private void btnModifierLimiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierLimiteActionPerformed
        //On recupere la valeur limite saisir
        String valeurSaisi = txtLimite.getText();
        boolean limiteEstInt = isInt(valeurSaisi);
        if(limiteEstInt){
            int nvLimite = Integer.parseInt(valeurSaisi);
            boolean limiteChange = gererBD.enregistrerLimiteCredit(margeCredit.getNumero(), nvLimite);
            if(limiteChange){
                lblLimite.setText(valeurSaisi);
                margeCredit.setLimite(nvLimite);
                txtLimite.setText("");
            }
        }
        else{
            // Valeur nom int
            frame.valeurIntLimiteCredit();
        }
        
    }//GEN-LAST:event_btnModifierLimiteActionPerformed

    private void btnPrelevementHypothecaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrelevementHypothecaireActionPerformed
        String prelevementSaisi = txtValeurPrelevementHypothecaire.getText();
        boolean valeurEstDouble = isDouble(prelevementSaisi);
        if(valeurEstDouble){
            double valeur = Double.parseDouble(prelevementSaisi);
            //On recupere la compte source
            String compteSourceItemRetrait = cbHypothecaires.getSelectedItem().toString();
       
            //On identifie le type de la compte et le numero
            String[] compteChoisi = compteSourceItemRetrait.split(" ");
            String numeroCompteSource = compteChoisi[1];
            String compteType = compteChoisi[0];
            int indexCompte = getIndexComptesHypothecaire(numeroCompteSource, hypothecaires);
            //On recupere la compreSource
            CompteHypothecaire ch = hypothecaires.get(indexCompte);
            boolean succes = ch.prelevement(valeur, margeCredit, gererBD);
            if(succes){
                //On remplit les comptes
                remplirComptes();
                //On remplit le cb
                remplirCbHypothecaires();
                gererBD.insererTransaction(5, ch.getNumero(), "", valeur);
                //On remplit la liste des transactions
                remplirListeTransactions();
                //On vide le txt
                txtValeurPrelevementHypothecaire.setText("");
                if(margeCredit != null)
                     lblCreditSolde.setText(String.format("%.2f", margeCredit.getSolde()));
            }
        }
        else{
            //valeur nom numerique
        }
    }//GEN-LAST:event_btnPrelevementHypothecaireActionPerformed

    private void btnInteretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInteretActionPerformed
        //On recupere la liste des comptes cheques
        chequesBanque = gererBD.retournerListCheque();
        int chequesSize = chequesBanque.size();
        
        for(int i = 0; i < chequesSize; i++){
            chequesBanque.get(i).payerInteret(gererBD);
        }  
        //On avise l'adm.
        frame.interetComptesCheques();
    }//GEN-LAST:event_btnInteretActionPerformed

    private void btnAjouterArgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterArgentActionPerformed
        boolean succes = guichet.setSoldePlus5k();
        if(succes)
            gererBD.enregistrerSoldeGuichet(guichet.getSolde());
    }//GEN-LAST:event_btnAjouterArgentActionPerformed

    private void btnClientStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientStatusActionPerformed
        //Si le client est bloqué on le debloque
        if(client.getEsssaieLogin() >= 3){
            client.setEssaieLogin(0);
            btnClientStatus.setText("Client actif");
            gererBD.loginClient(0, codeClient);
        }
        //Si le client n'est pas bloqué on le bloque
        else{
            client.setEssaieLogin(4);
            btnClientStatus.setText("Client bloqué");
            gererBD.loginClient(4, codeClient);
        }
        
    }//GEN-LAST:event_btnClientStatusActionPerformed

    private void btnTauxCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTauxCreditActionPerformed
        //On recupère les comptes credit
        creditsBanque = gererBD.retournerListCredit();
        int creditsSize = creditsBanque.size();
        //On aplique la taux de 5%
        for(int i = 0; i < creditsSize; i++){
            creditsBanque.get(i).interetCredit(gererBD);
        } 
        //On avise l'adm
        frame.interetCredit();
    }//GEN-LAST:event_btnTauxCreditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EcranAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EcranAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EcranAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EcranAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EcranAdmin().setVisible(true);
            }
        });
    }
    
    //METHODES 
    
    private int getIndexComptesHypothecaire(String numeroCompte, List<CompteHypothecaire>comptes){
             int numero = 0;
            for(int i = 0; i < comptes.size(); i++){
                if(numeroCompte.equals(comptes.get(i).getNumero())){
                    numero = i;
                }
            }
            return numero;
        }
    
    private boolean isInt(String str) { 
          try {  
            Integer.parseInt(str);  
            return true;
          } catch(NumberFormatException e){  
            return false;  
          }  
        }
        
    private boolean isDouble(String str) { 
          try {  
            Double.parseDouble(str);  
            return true;
          } catch(NumberFormatException e){  
            return false;  
          }  
        }
    
    private void remplirComptes(){
        //On vide les listes des comptes
        if(cheques != null)
            cheques.clear();
        if(epargnes != null)
            epargnes.clear();
        if(hypothecaires != null)
            hypothecaires.clear();
        
        //On ouvre la connexion sql
        connexion.connect();
        statement = connexion.statement();
        String query = "SELECT * FROM tbl_comptes WHERE codeTitulaire = '" + codeClient +"';";
        try{
            resultSet = statement.executeQuery(query);
            
            while(resultSet.next())
            {
                int compteType = resultSet.getInt("type");
                String numero = resultSet.getString("numero");
                double solde = resultSet.getDouble("solde");
                double limite = resultSet.getDouble("limite");
                
                if(compteType == 1){
                    CompteCheque compte = new CompteCheque(numero, codeClient);
                    compte.setSolde(solde);
                    cheques.add(compte);
                }
                else if(compteType == 2){
                    CompteEpargne compte = new CompteEpargne(numero, codeClient);
                    compte.setSolde(solde);
                    epargnes.add(compte);
                }
                else if(compteType == 3){
                    CompteHypothecaire compte = new CompteHypothecaire(numero, codeClient);
                    compte.setSolde(solde);
                    hypothecaires.add(compte);
                }
                else if(compteType == 4){
                    MargeDeCredit compte = new MargeDeCredit(numero, codeClient);
                    compte.setSolde(solde);
                    compte.setLimite((int)limite);
                    this.margeCredit = compte;
                }
                
                
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
        finally{
         connexion.deconnecter();
        }
    }
        
    private void remplirCbHypothecaires(){
        //On vide le CB
        cbHypothecaires.removeAllItems();
        
        //On ajoute les comptes cheques
        ajouterCbHypothecaires(hypothecaires.size(), cbHypothecaires);
    }
        
    public void ajouterCbHypothecaires(int quantiteHypothecaires, JComboBox cb){
        for(int i = 0; i < quantiteHypothecaires; i++ ){
            //On arroundi la solde de la compte
            double solde = hypothecaires.get(i).getSolde();
            //On utilise le NumberFormat pour afficher la valeur en dolar
            Locale locale = new Locale("en", "US");
            NumberFormat fmt = NumberFormat.getCurrencyInstance(locale);
            String soldeFormate = fmt.format(solde);
            //On cree une string pour l'item
            String cbItem = "Hypothecaire "+ hypothecaires.get(i).getNumero()+ " : Solde " + soldeFormate;
            //On ajoute l'item au CB
            cb.addItem(cbItem);
        }
    }
    
    private void remplirListeTransactions(){
        listTransactions.removeAll();
        DefaultListModel listModel = new DefaultListModel();
        for(int i = 0; i < transactions.size(); i++){
            
            int id = transactions.get(i).getNumeroTransaction();
            String type = recupererTypeTransaction(transactions.get(i).getTransactionType());
            String compteSource = transactions.get(i).getCompteSource();
            String compteDestin = transactions.get(i).getCompteDestin();
            Double valeur = transactions.get(i).getValeur();
            String quand = transactions.get(i).getQuand();
            
            String ligne = "ID: " + id + " " + type + "  Compte source: " + compteSource + "  Compte destin: " + compteDestin + "  Valeur: " + valeur + "  Quand: " + quand ;
            
            listModel.addElement(ligne);
        }
        listTransactions.setModel(listModel);
    }
    
    private String recupererTypeTransaction(int type){
        if(type == 1) return "Dépot";
        else if(type == 2) return "Retrait";
        else if(type == 3) return "Transfert";
        else return "Facture";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouterArgent;
    private javax.swing.JButton btnAjouterClient;
    private javax.swing.JButton btnChercherClient;
    private javax.swing.JButton btnClientStatus;
    private javax.swing.JButton btnCreerCompte;
    private javax.swing.JButton btnInteret;
    private javax.swing.JButton btnModifierLimite;
    private javax.swing.JButton btnPrelevementHypothecaire;
    private javax.swing.JButton btnTauxCredit;
    private javax.swing.JComboBox<String> cbHypothecaires;
    private javax.swing.JComboBox<String> cbTypeCompteCreer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCodeClient;
    private javax.swing.JLabel lblCreditSolde;
    private javax.swing.JLabel lblLimite;
    private javax.swing.JLabel lblNomC;
    private javax.swing.JLabel lblNomPrenomClient;
    private javax.swing.JLabel lblPrenomC;
    private javax.swing.JLabel lblTelephoneClient;
    private javax.swing.JList<String> listTransactions;
    private javax.swing.JTextField txtCodeClientChercher;
    private javax.swing.JTextField txtLimite;
    private javax.swing.JTextField txtNIPNvClient;
    private javax.swing.JTextField txtNomNvClient;
    private javax.swing.JTextField txtPrenomNvClient;
    private javax.swing.JTextField txtTelNvClient;
    private javax.swing.JTextField txtValeurPrelevementHypothecaire;
    // End of variables declaration//GEN-END:variables
}
